# Max of list

In [13]:
import numpy as np
lst = np.random.randint(0,10,10)
lst[0]


# lst = [1,2,3,4]
# find the max
print(lst)

[8 8 8 9 5 6 3 2 4 2]


In [17]:
lst = np.random.randint(0,10,10)
lst

array([9, 8, 0, 9, 3, 6, 2, 1, 6, 3])

In [14]:
# 
max_num = 0
for i in lst:
    if i > max_num:
        max_num = i
    else:
        pass
max_num

9

In [15]:
max(lst)

9

In [19]:
# Each data point represents one day in the month of August 2000. 
# e.g. the first data point was the avg daily temperature on August 1, 2000
paris = [75.9, 67.2, 64.2, 63.3, 65.5, 67.0, 70.3, 68.1, 70.9, 68.0, 69.9, 74.0, 77.1, 74.1, 70.0, 69.8, 69.9, 67.9, 65.9, 63.3, 62.4, 63.8, 68.6, 73.3, 75.8, 70.7, 63.5, 64.6, 66.4, 66.4, 65.3]
helsinki = [60.2, 62.1, 61.7, 61.7, 60.2, 62.7, 61.9, 58.6, 56.8, 59.8, 59.9, 61.8, 63.0, 63.9, 60.1, 64.5, 59.5, 57.4, 60.3, 60.2, 60.4, 58.9, 54.6, 54.3, 57.2, 58.9, 58.5, 59.0, 59.2, 61.1, 60.9]
copenhagen = [61.2, 62.4, 60.6, 60.6, 59.0, 61.5, 57.6, 57.5, 58.8, 57.5, 60.5, 59.5, 58.6, 61.7, 65.5, 60.6, 60.2, 60.5, 60.3, 60.9, 57.4, 56.2, 56.3, 55.9, 57.9, 58.4, 62.0, 61.0, 61.8, 57.6, 55.5]
rome = [73.9, 73.5, 73.6, 75.2, 71.8, 70.0, 71.4, 73.7, 73.3, 74.5, 74.9, 74.4, 79.5, 76.0, 76.8, 78.3, 77.1, 77.4, 76.4, 77.2, 77.9, 78.7, 79.6, 79.9, 77.6, 78.4, 77.8, 77.4, 76.5, 73.8, 74.9]
madrid = [83.8, 83.8, 73.6, 67.9, 68.0, 70.5, 73.2, 75.0, 78.7, 81.2, 76.7, 74.8, 78.7, 78.7, 84.6, 83.9, 83.6, 82.3, 79.3, 75.7, 73.6, 68.6, 68.8, 73.9, 76.0, 71.9, 71.8, 73.8, 77.3, 75.9, 71.7]
stockholm = [65.9, 62.7, 60.5, 63.9, 63.9, 63.9, 61.0, 58.1, 62.5, 63.1, 64.1, 63.6, 61.3, 64.4, 65.3, 63.6, 62.6, 62.1, 63.3, 60.3, 61.1, 59.4, 57.5, 54.7, 57.0, 61.4, 62.1, 62.4, 62.7, 61.0, 56.5]
london = [66.6, 63.1, 61.3, 63.9, 65.1, 68.7, 68.0, 66.8, 65.4, 67.8, 67.6, 68.8, 65.9, 67.6, 65.6, 65.6, 63.0, 62.2, 64.9, 63.4, 60.8, 62.4, 64.8, 67.8, 68.3, 65.7, 61.5, 60.4, 61.2, 62.3, 61.1]

In [21]:
import pandas as pd

In [22]:
df = pd.DataFrame(
    {
        "Paris" : paris, 
        "Helsinki" : helsinki,
        "Copenhagen" : copenhagen,
        "Rome" : rome, 
        "Madrid" : madrid, 
        "Stockholm":stockholm,
        "London" : london
    }
)
df.head(5)

Paris  Helsinki  Copenhagen  Rome  Madrid  Stockholm  London
0   75.9      60.2        61.2  73.9    83.8       65.9    66.6
1   67.2      62.1        62.4  73.5    83.8       62.7    63.1
2   64.2      61.7        60.6  73.6    73.6       60.5    61.3
3   63.3      61.7        60.6  75.2    67.9       63.9    63.9
4   65.5      60.2        59.0  71.8    68.0       63.9    65.1

In [34]:
for i in df.columns:
    print(i, df.max()- df.min())

Paris Paris         14.7
Helsinki      10.2
Copenhagen    10.0
Rome           9.9
Madrid        16.7
Stockholm     11.2
London         8.4
dtype: float64
Helsinki Paris         14.7
Helsinki      10.2
Copenhagen    10.0
Rome           9.9
Madrid        16.7
Stockholm     11.2
London         8.4
dtype: float64
Copenhagen Paris         14.7
Helsinki      10.2
Copenhagen    10.0
Rome           9.9
Madrid        16.7
Stockholm     11.2
London         8.4
dtype: float64
Rome Paris         14.7
Helsinki      10.2
Copenhagen    10.0
Rome           9.9
Madrid        16.7
Stockholm     11.2
London         8.4
dtype: float64
Madrid Paris         14.7
Helsinki      10.2
Copenhagen    10.0
Rome           9.9
Madrid        16.7
Stockholm     11.2
London         8.4
dtype: float64
Stockholm Paris         14.7
Helsinki      10.2
Copenhagen    10.0
Rome           9.9
Madrid        16.7
Stockholm     11.2
London         8.4
dtype: float64
London Paris         14.7
Helsinki      10.2
Copenhagen    10.0


In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Paris       31 non-null     float64
 1   Helsinki    31 non-null     float64
 2   Copenhagen  31 non-null     float64
 3   Rome        31 non-null     float64
 4   Madrid      31 non-null     float64
 5   Stockholm   31 non-null     float64
 6   London      31 non-null     float64
dtypes: float64(7)
memory usage: 1.8 KB


In [29]:
df.describe()

Paris   Helsinki  Copenhagen       Rome     Madrid  Stockholm  \
count  31.000000  31.000000   31.000000  31.000000  31.000000  31.000000   
mean   68.487097  59.977419   59.516129  75.851613  76.041935  61.674194   
std     4.082380   2.353963    2.263345   2.527300   5.059563   2.665579   
min    62.400000  54.300000   55.500000  70.000000  67.900000  54.700000   
25%    65.400000  58.900000   57.600000  73.850000  72.550000  60.750000   
50%    68.000000  60.200000   60.200000  76.400000  75.700000  62.400000   
75%    70.500000  61.700000   60.950000  77.700000  79.000000  63.600000   
max    77.100000  64.500000   65.500000  79.900000  84.600000  65.900000   

          London  
count  31.000000  
mean   64.761290  
std     2.653008  
min    60.400000  
25%    62.350000  
50%    65.100000  
75%    67.200000  
max    68.800000

In [31]:
df.T.describe()

0          1          2          3          4          5   \
count   7.000000   7.000000   7.000000   7.000000   7.000000   7.000000   
mean   69.642857  67.828571  65.071429  65.214286  64.785714  66.328571   
std     8.577268   8.150606   5.954190   4.961327   4.386125   3.636259   
min    60.200000  62.100000  60.500000  60.600000  59.000000  61.500000   
25%    63.550000  62.550000  60.950000  62.500000  62.050000  63.300000   
50%    66.600000  63.100000  61.700000  63.900000  65.100000  67.000000   
75%    74.900000  70.350000  68.900000  65.900000  66.750000  69.350000   
max    83.800000  83.800000  73.600000  75.200000  71.800000  70.500000   

              6          7          8          9   ...         21         22  \
count   7.000000   7.000000   7.000000   7.000000  ...   7.000000   7.000000   
mean   66.200000  65.400000  66.628571  67.414286  ...  64.000000  64.314286   
std     5.994164   7.441326   8.009518   8.322946  ...   7.614241   8.920095   
min    57.600000  57.500000  56.800000  57.500000  ...  56.200000  54.600000   
25%    61.450000  58.350000  60.650000  61.450000  ...  59.150000  56.900000   
50%    68.000000  66.800000  65.400000  67.800000  ...  62.400000  64.800000   
75%    70.850000  70.900000  72.100000  71.250000  ...  66.200000  68.700000   
max    73.200000  75.000000  78.700000  81.200000  ...  78.700000  79.600000   

              23         24         25         26         27         28  \
count   7.000000   7.000000   7.000000   7.000000   7.000000   7.000000   
mean   65.685714  67.114286  66.485714  65.314286  65.514286  66.442857   
std    10.630527   9.585132   7.510310   6.874452   7.181325   7.467007   
min    54.300000  57.000000  58.400000  58.500000  59.000000  59.200000   
25%    55.300000  57.550000  60.150000  61.750000  60.700000  61.500000   
50%    67.800000  68.300000  65.700000  62.100000  62.400000  62.700000   
75%    73.600000  75.900000  71.300000  67.650000  69.200000  71.450000   
max    79.900000  77.600000  78.400000  77.800000  77.400000  77.300000   

              29         30  
count   7.000000   7.000000  
mean   65.442857  63.700000  
std     6.953382   7.367496  
min    57.600000  55.500000  
25%    61.050000  58.700000  
50%    62.300000  61.100000  
75%    70.100000  68.500000  
max    75.900000  74.900000  

[8 rows x 31 columns]

In [23]:
df.max()

Paris         77.1
Helsinki      64.5
Copenhagen    65.5
Rome          79.9
Madrid        84.6
Stockholm     65.9
London        68.8
dtype: float64

In [24]:
df.max().max()

84.6

In [25]:
df.min().min()

54.3

In [27]:
(df.max() - df.min()).max()

16.69999999999999

In [36]:
df.head(10)

Paris  Helsinki  Copenhagen  Rome  Madrid  Stockholm  London
0   75.9      60.2        61.2  73.9    83.8       65.9    66.6
1   67.2      62.1        62.4  73.5    83.8       62.7    63.1
2   64.2      61.7        60.6  73.6    73.6       60.5    61.3
3   63.3      61.7        60.6  75.2    67.9       63.9    63.9
4   65.5      60.2        59.0  71.8    68.0       63.9    65.1
5   67.0      62.7        61.5  70.0    70.5       63.9    68.7
6   70.3      61.9        57.6  71.4    73.2       61.0    68.0
7   68.1      58.6        57.5  73.7    75.0       58.1    66.8
8   70.9      56.8        58.8  73.3    78.7       62.5    65.4
9   68.0      59.8        57.5  74.5    81.2       63.1    67.8

In [37]:
df.tail(10)

Paris  Helsinki  Copenhagen  Rome  Madrid  Stockholm  London
21   63.8      58.9        56.2  78.7    68.6       59.4    62.4
22   68.6      54.6        56.3  79.6    68.8       57.5    64.8
23   73.3      54.3        55.9  79.9    73.9       54.7    67.8
24   75.8      57.2        57.9  77.6    76.0       57.0    68.3
25   70.7      58.9        58.4  78.4    71.9       61.4    65.7
26   63.5      58.5        62.0  77.8    71.8       62.1    61.5
27   64.6      59.0        61.0  77.4    73.8       62.4    60.4
28   66.4      59.2        61.8  76.5    77.3       62.7    61.2
29   66.4      61.1        57.6  73.8    75.9       61.0    62.3
30   65.3      60.9        55.5  74.9    71.7       56.5    61.1

In [38]:
df.sample(10)

Paris  Helsinki  Copenhagen  Rome  Madrid  Stockholm  London
1    67.2      62.1        62.4  73.5    83.8       62.7    63.1
16   69.9      59.5        60.2  77.1    83.6       62.6    63.0
8    70.9      56.8        58.8  73.3    78.7       62.5    65.4
14   70.0      60.1        65.5  76.8    84.6       65.3    65.6
29   66.4      61.1        57.6  73.8    75.9       61.0    62.3
20   62.4      60.4        57.4  77.9    73.6       61.1    60.8
0    75.9      60.2        61.2  73.9    83.8       65.9    66.6
19   63.3      60.2        60.9  77.2    75.7       60.3    63.4
25   70.7      58.9        58.4  78.4    71.9       61.4    65.7
23   73.3      54.3        55.9  79.9    73.9       54.7    67.8

In [39]:
df.iloc[10:20]

Paris  Helsinki  Copenhagen  Rome  Madrid  Stockholm  London
10   69.9      59.9        60.5  74.9    76.7       64.1    67.6
11   74.0      61.8        59.5  74.4    74.8       63.6    68.8
12   77.1      63.0        58.6  79.5    78.7       61.3    65.9
13   74.1      63.9        61.7  76.0    78.7       64.4    67.6
14   70.0      60.1        65.5  76.8    84.6       65.3    65.6
15   69.8      64.5        60.6  78.3    83.9       63.6    65.6
16   69.9      59.5        60.2  77.1    83.6       62.6    63.0
17   67.9      57.4        60.5  77.4    82.3       62.1    62.2
18   65.9      60.3        60.3  76.4    79.3       63.3    64.9
19   63.3      60.2        60.9  77.2    75.7       60.3    63.4

In [46]:
df.describe().T

count       mean       std   min    25%   50%    75%   max
Paris        31.0  68.487097  4.082380  62.4  65.40  68.0  70.50  77.1
Helsinki     31.0  59.977419  2.353963  54.3  58.90  60.2  61.70  64.5
Copenhagen   31.0  59.516129  2.263345  55.5  57.60  60.2  60.95  65.5
Rome         31.0  75.851613  2.527300  70.0  73.85  76.4  77.70  79.9
Madrid       31.0  76.041935  5.059563  67.9  72.55  75.7  79.00  84.6
Stockholm    31.0  61.674194  2.665579  54.7  60.75  62.4  63.60  65.9
London       31.0  64.761290  2.653008  60.4  62.35  65.1  67.20  68.8

In [47]:
# range
for i in df.columns:
    print(f"%s\n%d\n" %(i, (df[i].max() - df[i].min())))

Paris
14

Helsinki
10

Copenhagen
10

Rome
9

Madrid
16

Stockholm
11

London
8



In [49]:
df.Paris.diff()

0     NaN
1    -8.7
2    -3.0
3    -0.9
4     2.2
5     1.5
6     3.3
7    -2.2
8     2.8
9    -2.9
10    1.9
11    4.1
12    3.1
13   -3.0
14   -4.1
15   -0.2
16    0.1
17   -2.0
18   -2.0
19   -2.6
20   -0.9
21    1.4
22    4.8
23    4.7
24    2.5
25   -5.1
26   -7.2
27    1.1
28    1.8
29    0.0
30   -1.1
Name: Paris, dtype: float64

In [53]:
df.Paris.diff().fillna(df.Paris.iloc[-1] - df.Paris.iloc[0])

0    -10.6
1     -8.7
2     -3.0
3     -0.9
4      2.2
5      1.5
6      3.3
7     -2.2
8      2.8
9     -2.9
10     1.9
11     4.1
12     3.1
13    -3.0
14    -4.1
15    -0.2
16     0.1
17    -2.0
18    -2.0
19    -2.6
20    -0.9
21     1.4
22     4.8
23     4.7
24     2.5
25    -5.1
26    -7.2
27     1.1
28     1.8
29     0.0
30    -1.1
Name: Paris, dtype: float64

# Find delta

In [70]:
# 
lst = np.random.randint(0,100,10)
lst = [3,4,5]

def find_delta(lst):
    delta_lst = []
    for i in range(0,len(lst),1):
        delta_lst.append(lst[i]- lst[i+1] )    
    return delta_lst

In [71]:
print(lst)

[3, 4, 5]


In [72]:
print(find_delta(lst))

IndexError: list index out of range

# Reverse a list

In [90]:
lst = np.random.randint(0,10,10)

lst = lst.tolist()
lst

[0 9 2 3 5 7 9 3 8 4]


[0, 9, 2, 3, 5, 7, 9, 3, 8, 4]

In [88]:
my_lst = []
for i in range(0,len(lst),1):
    value= lst.pop()
    print(value)
    my_lst.append(value)

1
6
9
2
8
9
6
1
4
7


In [89]:
my_lst

[1, 6, 9, 2, 8, 9, 6, 1, 4, 7]

In [93]:
np.random.randint(0,10,10)
print(type(lst.tolist()))

<class 'list'>
